# Generated by Django 3.0.4 on 2020-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(max_length=155),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
