# Generated by Django 2.2.10 on 2020-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0014_auto_20200401_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introtext', models.CharField(max_length=255)),
                ('missionheading', models.CharField(max_length=30)),
                ('mission', models.CharField(max_length=255)),
                ('visionheading', models.CharField(max_length=30)),
                ('visiontext', models.CharField(max_length=255)),
            ],
        ),
    ]
