# Generated by Django 2.2.10 on 2020-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0015_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='mission',
            new_name='missiontext',
        ),
        migrations.AlterField(
            model_name='about',
            name='introtext',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='visionheading',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='about',
            name='visiontext',
            field=models.TextField(max_length=255),
        ),
    ]
