# Generated by Django 2.2.10 on 2020-04-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0016_auto_20200403_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='missiontext',
            field=models.TextField(max_length=255),
        ),
    ]
