# Generated by Django 2.2.10 on 2020-04-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0018_auto_20200403_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='introtext',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='missiontext',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='visiontext',
            field=models.TextField(max_length=500),
        ),
    ]
