# Generated by Django 2.2.10 on 2020-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0019_auto_20200403_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiambu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestarted', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Muranga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestarted', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Nairobi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestarted', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Nakuru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestarted', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Nyeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestarted', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(max_length=155)),
            ],
        ),
    ]
