# Generated by Django 2.2.10 on 2020-04-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0020_kiambu_muranga_nairobi_nakuru_nyeri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='careers',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Careers'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='kiambu',
            options={'verbose_name_plural': 'Kiambu'},
        ),
        migrations.AlterModelOptions(
            name='muranga',
            options={'verbose_name_plural': 'Muranga'},
        ),
        migrations.AlterModelOptions(
            name='nairobi',
            options={'verbose_name_plural': 'Nairobi'},
        ),
        migrations.AlterModelOptions(
            name='nakuru',
            options={'verbose_name_plural': 'Nakuru'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['pub_date'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='nyeri',
            options={'verbose_name_plural': 'Nyeri'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name_plural': 'Testimonials'},
        ),
    ]
