# Generated by Django 2.2.10 on 2020-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0021_auto_20200403_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiambu',
            name='datestarted',
        ),
        migrations.RemoveField(
            model_name='kiambu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kiambu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kiambu',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kiambu',
            name='title',
        ),
        migrations.RemoveField(
            model_name='muranga',
            name='datestarted',
        ),
        migrations.RemoveField(
            model_name='muranga',
            name='description',
        ),
        migrations.RemoveField(
            model_name='muranga',
            name='image',
        ),
        migrations.RemoveField(
            model_name='muranga',
            name='location',
        ),
        migrations.RemoveField(
            model_name='muranga',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nairobi',
            name='datestarted',
        ),
        migrations.RemoveField(
            model_name='nairobi',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nairobi',
            name='location',
        ),
        migrations.RemoveField(
            model_name='nairobi',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nakuru',
            name='datestarted',
        ),
        migrations.RemoveField(
            model_name='nakuru',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nakuru',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nakuru',
            name='location',
        ),
        migrations.RemoveField(
            model_name='nakuru',
            name='title',
        ),
        migrations.RemoveField(
            model_name='nyeri',
            name='datestarted',
        ),
        migrations.RemoveField(
            model_name='nyeri',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nyeri',
            name='image',
        ),
        migrations.RemoveField(
            model_name='nyeri',
            name='location',
        ),
        migrations.RemoveField(
            model_name='nyeri',
            name='title',
        ),
        migrations.AddField(
            model_name='kiambu',
            name='ProgramDescription',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kiambu',
            name='ProgramImage',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='kiambu',
            name='ProgramLocation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kiambu',
            name='ProgramOnset',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='kiambu',
            name='ProgramTitle',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='muranga',
            name='ProgramDescription',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='muranga',
            name='ProgramImage',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='muranga',
            name='ProgramLocation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='muranga',
            name='ProgramOnset',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='muranga',
            name='ProgramTitle',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='nairobi',
            name='ProgramDescription',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nairobi',
            name='ProgramLocation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nairobi',
            name='ProgramOnset',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='nairobi',
            name='ProgramTitle',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='nakuru',
            name='ProgramDescription',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nakuru',
            name='ProgramImage',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nakuru',
            name='ProgramLocation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nakuru',
            name='ProgramOnset',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='nakuru',
            name='ProgramTitle',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='nyeri',
            name='ProgramDescription',
            field=models.TextField(default=True, max_length=500),
        ),
        migrations.AddField(
            model_name='nyeri',
            name='ProgramImage',
            field=models.ImageField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nyeri',
            name='ProgramLocation',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='nyeri',
            name='ProgramOnset',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='nyeri',
            name='ProgramTitle',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='nairobi',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
