# Generated by Django 2.2.10 on 2020-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0024_auto_20200403_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiambu',
            name='donate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
