# Generated by Django 2.2.10 on 2020-04-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0027_faq_youthgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='pastevents',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
