# Generated by Django 2.0 on 2020-03-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('venue', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=155)),
            ],
        ),
    ]
