# Generated by Django 3.0.4 on 2020-03-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joy', '0005_auto_20200324_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsimage', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
